// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: roof.proto

package roof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PerformAnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmap []byte `protobuf:"bytes,1,opt,name=cmap,proto3" json:"cmap,omitempty"` // image
	Emap []byte `protobuf:"bytes,2,opt,name=emap,proto3" json:"emap,omitempty"` // elevation map
}

func (x *PerformAnalysisRequest) Reset() {
	*x = PerformAnalysisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerformAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformAnalysisRequest) ProtoMessage() {}

func (x *PerformAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformAnalysisRequest.ProtoReflect.Descriptor instead.
func (*PerformAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_roof_proto_rawDescGZIP(), []int{0}
}

func (x *PerformAnalysisRequest) GetCmap() []byte {
	if x != nil {
		return x.Cmap
	}
	return nil
}

func (x *PerformAnalysisRequest) GetEmap() []byte {
	if x != nil {
		return x.Emap
	}
	return nil
}

type PerformAnalysisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // roof id
}

func (x *PerformAnalysisResponse) Reset() {
	*x = PerformAnalysisResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerformAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformAnalysisResponse) ProtoMessage() {}

func (x *PerformAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformAnalysisResponse.ProtoReflect.Descriptor instead.
func (*PerformAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_roof_proto_rawDescGZIP(), []int{1}
}

func (x *PerformAnalysisResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetrieveAnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // roof id
}

func (x *RetrieveAnalysisRequest) Reset() {
	*x = RetrieveAnalysisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveAnalysisRequest) ProtoMessage() {}

func (x *RetrieveAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveAnalysisRequest.ProtoReflect.Descriptor instead.
func (*RetrieveAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_roof_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveAnalysisRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetrieveAnalysisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmap  []byte `protobuf:"bytes,1,opt,name=cmap,proto3" json:"cmap,omitempty"`   // image
	Msmap []byte `protobuf:"bytes,2,opt,name=msmap,proto3" json:"msmap,omitempty"` // final mask
}

func (x *RetrieveAnalysisResponse) Reset() {
	*x = RetrieveAnalysisResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roof_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveAnalysisResponse) ProtoMessage() {}

func (x *RetrieveAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roof_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveAnalysisResponse.ProtoReflect.Descriptor instead.
func (*RetrieveAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_roof_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveAnalysisResponse) GetCmap() []byte {
	if x != nil {
		return x.Cmap
	}
	return nil
}

func (x *RetrieveAnalysisResponse) GetMsmap() []byte {
	if x != nil {
		return x.Msmap
	}
	return nil
}

type Polygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*Point2D `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roof_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_roof_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_roof_proto_rawDescGZIP(), []int{4}
}

func (x *Polygon) GetPoints() []*Point2D {
	if x != nil {
		return x.Points
	}
	return nil
}

type Point2D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point2D) Reset() {
	*x = Point2D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roof_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point2D) ProtoMessage() {}

func (x *Point2D) ProtoReflect() protoreflect.Message {
	mi := &file_roof_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point2D.ProtoReflect.Descriptor instead.
func (*Point2D) Descriptor() ([]byte, []int) {
	return file_roof_proto_rawDescGZIP(), []int{5}
}

func (x *Point2D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point2D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roof_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_roof_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_roof_proto_rawDescGZIP(), []int{6}
}

func (x *PingMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_roof_proto protoreflect.FileDescriptor

var file_roof_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x6f,
	0x6f, 0x66, 0x22, 0x40, 0x0a, 0x16, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x6d, 0x61, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x65, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x65, 0x6d, 0x61, 0x70, 0x22, 0x29, 0x0a, 0x17, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x41,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x29, 0x0a, 0x17, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x18, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6d, 0x61, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x6d, 0x61, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73,
	0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x73, 0x6d, 0x61, 0x70,
	0x22, 0x30, 0x0a, 0x07, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x06, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f,
	0x6f, 0x66, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x44, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x25, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x44, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x69, 0x6e,
	0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0xee, 0x01, 0x0a, 0x15, 0x52, 0x6f, 0x6f, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x04,
	0x50, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x11, 0x2e, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0f,
	0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12,
	0x1c, 0x2e, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53,
	0x0a, 0x10, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x69, 0x73, 0x12, 0x1d, 0x2e, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_roof_proto_rawDescOnce sync.Once
	file_roof_proto_rawDescData = file_roof_proto_rawDesc
)

func file_roof_proto_rawDescGZIP() []byte {
	file_roof_proto_rawDescOnce.Do(func() {
		file_roof_proto_rawDescData = protoimpl.X.CompressGZIP(file_roof_proto_rawDescData)
	})
	return file_roof_proto_rawDescData
}

var file_roof_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_roof_proto_goTypes = []interface{}{
	(*PerformAnalysisRequest)(nil),   // 0: roof.PerformAnalysisRequest
	(*PerformAnalysisResponse)(nil),  // 1: roof.PerformAnalysisResponse
	(*RetrieveAnalysisRequest)(nil),  // 2: roof.RetrieveAnalysisRequest
	(*RetrieveAnalysisResponse)(nil), // 3: roof.RetrieveAnalysisResponse
	(*Polygon)(nil),                  // 4: roof.Polygon
	(*Point2D)(nil),                  // 5: roof.Point2D
	(*PingMessage)(nil),              // 6: roof.PingMessage
}
var file_roof_proto_depIdxs = []int32{
	5, // 0: roof.Polygon.points:type_name -> roof.Point2D
	6, // 1: roof.RoofServiceProcedures.Ping:input_type -> roof.PingMessage
	0, // 2: roof.RoofServiceProcedures.PerformAnalysis:input_type -> roof.PerformAnalysisRequest
	2, // 3: roof.RoofServiceProcedures.RetrieveAnalysis:input_type -> roof.RetrieveAnalysisRequest
	6, // 4: roof.RoofServiceProcedures.Ping:output_type -> roof.PingMessage
	1, // 5: roof.RoofServiceProcedures.PerformAnalysis:output_type -> roof.PerformAnalysisResponse
	3, // 6: roof.RoofServiceProcedures.RetrieveAnalysis:output_type -> roof.RetrieveAnalysisResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_roof_proto_init() }
func file_roof_proto_init() {
	if File_roof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_roof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerformAnalysisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerformAnalysisResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveAnalysisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roof_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveAnalysisResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roof_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Polygon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roof_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point2D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roof_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roof_proto_goTypes,
		DependencyIndexes: file_roof_proto_depIdxs,
		MessageInfos:      file_roof_proto_msgTypes,
	}.Build()
	File_roof_proto = out.File
	file_roof_proto_rawDesc = nil
	file_roof_proto_goTypes = nil
	file_roof_proto_depIdxs = nil
}
